[package]
name = "jdx"
version = "0.4.0-alpha"
edition = "2021"

[workspace]
members = ["libjdx-sys"]

[dependencies]
libjdx-sys = { path = "libjdx-sys", version = "0.4.0-alpha" }
libc = "0.2"

[dev-dependencies]
lazy_static = "1.4"
